classdef Fred
    % This class was created to hold Federal Reserve Data 
    % From FRED the Federal Reserve Bank of St Louis
    % 
    % Written By:Stephen Forczyk
    % Created: June 18,2025
    % Revised: Feb 19,2026 added entries for exchage rate
    % Revised: Mar 10,2026
    % Revised: April 1-15,2026
    % Revised: June 10-12,2026 added additional commodity price data
    properties
        fredfile1='UNRATE-1948-2024.xlsx';
        fredfile2='CORESTICKM159SFRBATL.xlsx';
        fredfile3='CIVPART-1948-2025.xlsx';
        fredfile4='DelinquencyRateSingleHomes-1991-2025.xlsx';
        fredfile5='HomeOwnership-1965-2025.xlsx';
        fredfile6='IPMAN-1972-2025.xlsx';
        fredfile7='RealMedianHouseholdIncome.xlsx';
        fredfile8='CBOE-VIX.xlsx';
        fredfile9='ConsumerConfidence-1978-2025.xlsx';
        fredfile10='HouseInventory.xlsx';
        fredfile11='Fed10YearBondYields.xlsx';
        fredfile12='U2Rate-1967-2025.xlsx';
        fredfile13='RealGDP-1947-2025.xlsx';
        fredfile14='RealGDPPerCap-1947-2025.xlsx';
        fredfile15='Fed2YearBondYields.xlsx';
        fredfile16='InitialUnemploymentClaims.xlsx';
        fredfile17='ContinuedUnemploymentClaims.xlsx';
        fredfile18='TotalNonFarmJobOpen-2000-2025.xlsx';
        fredfile19='ConstructionJobOpenings-2000-2025.xlsx';
        fredfile20='ManufacturingJobOpenings-2000-2025.xlsx';
        fredfile21='ProfJobOpen.xlsx';
        fredfile22='HealthCareJobOpenings.xlsx';
        fredfile23='GovJobOpenings.xlsx';
        fredfile24='RealMedianPersonalIncome.xlsx';
        fredfile25='T10Y2Y-1976-2025.xlsx';
        fredfile26='VISASMIDNSA-2014-2025.xlsx';
        fredfile27='CaseShillerHousePriceIndex.xlsx';
        fredfile28='MedianWeeklyWage.xlsx';
        fredfile29='FYGDP-1930-2023.xlsx'
        fredfile30='PublicDebtvsGDP-1966-2025.xlsx';
        fredfile31='BudgetSurplus.xlsx';
        fredfile32='NetFedOutlays.xlsx';
        fredfile33='FederalReceipts.xlsx';
        fredfile34='FederalPublicDebt.xlsx';
        fredfile35='FedInterestPctGDP.xlsx';
        fredfile36='TreasuryDebt.xlsx';
        fredfile37='DomesticAutoInventories.xlsx';
        fredfile38='ForeignAutoSales.xlsx';
        fredfile39='TotalVehicleSales.xlsx';
        fredfile40='DomesticAutoProduction.xlsx';
        fredfile41='AutoExports.xlsx';
        fredfile42='VehicleMilesTravelled.xlsx';
        fredfile43='FreightTransportIndex.xlsx';
        fredfile44='RailCarloads.xlsx';
        fredfile45='AirlineLoadfactor.xlsx';
        fredfile46='ASM.xlsx';
        fredfile47='PipelinePetrol.xlsx';
        fredfile48='HouseStarts.xlsx';
        fredfile49='MDSP.xlsx';
        fredfile50='VacantHousingUnits.xlsx';
        fredfile51='USPatents.xlsx';
        fredfile52='TCU.xlsx';
        fredfile53='IPSemiconductors.xlsx';
        fredfile54='IPDefense.xlsx';
        fredfile55='TotalRevenueAllHospitals.xlsx';
        fredfile56='PharmaceuticalPriceIndex.xlsx';
        fredfile57='ProducerPriceIndex.xlsx';
        fredfile58='FlexCPIIndex.xlsx';
        fredfile59='COMPU1USA.xlsx'
        fredfile60='AdvanceRetailSales.xlsx';
        fredfile61='ECommerceRSales.xlsx';
        fredfile62='InventoryToSales.xlsx';
        fredfile63='RetailInventories.xlsx';
        fredfile64='UsedCarSales.xlsx';
        fredfile65='RestaurantSales.xlsx';
        fredfile66='FurnitureSales.xlsx';
        fredfile67='ManufacturingSales.xlsx';
        fredfile68='NewCarSales.xlsx';
        fredfile69='FullServeRestaurants.xlsx';
        fredfile70='RetailGasSales.xlsx';
        fredfile71='RetailAutoParts.xlsx';
        fredfile72='LeadingIndex.xlsx';
        fredfile73='InferredRecessionDates.xlsx';
        fredfile74='CoincidentEconomicActivity.xlsx';
        fredfile75='BalanceSheets.xlsx';
        fredfile76='CreditCardDebt.xlsx';
        fredfile77='LoanPerformance.xlsx';
        fredfile78='Population.xlsx';
        fredfile79='TotalHouseHolds.xlsx';
        fredfile80='POP55.xlsx';
        fredfile81='POP-25-54.xlsx';
        fredfile82='FamiliesWithChildren.xlsx';
        fredfile83='BlackPop.xlsx';
        fredfile84='WhitePop.xlsx';
        fredfile85='HispanicPop.xlsx';
        fredfile86='FemaleEmploymentRatio.xlsx';
        fredfile87='CBOENasdaqVolatility.xlsx';
        fredfile88='LeadingIndexUSA.xlsx';
        fredfile89='Fed3MonthBondYields.xlsx';
        fredfile90='TDSP.xlsx';
        fredfile91='CDSP.xlsx';
        fredfile92='RealDisposableIncome.xlsx';
        fredfile93='PCE.xlsx';
        fredfile94='DAUTOSAAR.xlsx';
        fredfile95='USSTHPI.xlsx';
        fredfile96='RCCCBBALTOT.xlsx';
        fredfile97='RCMFLOORIG.xlsx';
        fredfile98='PastDueMortgages.xlsx';
        fredfile99='CreditScore50.xlsx';
        fredfile100='HomeEquityLines.xlsx';
        fredfile101='USDToPoundSterling.xlsx';
        fredfile102='NominalBroadUSDollarIndex.xlsx';
        fredfile103='JapaneseYenToUSD.xlsx';
        fredfile104='StockMarketCapitalization.xlsx';
        fredfile105='CPI_All.xlsx';
        fredfile106='GrossNationalIncome.xlsx'
        fredfile107='GASREGW.xlsx'
        fredfile108='DCOILBRENTEU.xlsx';
        fredfile109='EggPrices.xlsx';
        fredfile110='GroundBeefPrices.xlsx';
        fredfile111='ElectricityPrices.xlsx';
        fredfile112='WestTexasIntermediateCrude.xlsx';
        fredfile113='HenryHubNaturalGasPrices.xlsx';
        fredfile114='GlobalCopperPrice.xlsx';
        fredfile115='DieselPricesPrices.xlsx';
        fredfile116='JetFuelPrices.xlsx';
        fredfile117='GlobalAluminumPrice.xlsx';
        fredfile118='CocoaPrice.xlsx';
        fredfile119='GlobalEnergyPrice.xlsx';
        fredfile120='BreadPrice.xlsx';
        fredfile121='WheatPrices.xlsx';
        fredfile122='UraniumPrices.xlsx';
        fredfile123='NickelPrices.xlsx';
        fredfile124='RubberPrices.xlsx';
        fredfile125='SugarPrices.xlsx';
        fredfile126='CPIUrbanFoodAtHome.xlsx';
        fredfile127='PPIFoodManufacturing.xlsx';
        fredfile128='PPIDiesel.xlsx';
        fredfile129='BolognaPrices.xlsx';
        fredfile130='BonelessHamPrices.xlsx';
        fredfile131='ChuckRoastPrices.xlsx';
        fredfile132='BaconPrices.xlsx';
        fredfile133='SoybeanIndex.xlsx';
        fredfile134='FlourPrice.xlsx';
        fredfile135='CookingOilPriceIndex.xlsx';
        fredfile136='WholeChickenPrices.xlsx';
        fredfile137='PPIFarmProducts.xlsx';
        fredfile138='PPICattle.xlsx';
        fredfile139='PPITomatoes.xlsx';
        fredfile140='PPICorn.xlsx';
        fredfile141='PPIRawMilk.xlsx';
        fredfile142='PPIFruits.xlsx';
        fredfile143='PPICabbage.xlsx';
        fredfile144='PPIRice.xlsx';
        fredfile145='PPICitrusFruits.xlsx';
        fredfile146='RecessProb.xlsx';
        numitems=146;
        fredpath='K:\Investing2\FRED_Data\';
        Catalog=[]; % Catalog List of Fred Files
        UnrateTT=[];% Use fredfile1
        SCPITT=[];% used fredfile2
        ParticipationTT=[];% used frefile 3
        SingleHomeDelRateTT=[];% used fredfile 4
        HomeOwnershipTT=[];% used fredfile 5
        IPMANTT=[];% used fredfile 6
        RealMedHouseIncTT=[];% used fredfile 7
        VixTT=[];% used fredfile 8
        CCTT=[];% used fredfile 9
        HouseSupplyTT=[];%used fredfile 10
        Fed10YearBondsTT=[];% used fredfile 11
        U2RateTT=[];% used fredfile 12
        GDPTT=[];% used fredfile 13
        GDPPerCapTT=[];%used fredfile 14
        Fed2YearBondsTT=[];%used fredfile 15
        InitialUnemploymentTT=[];% used fredfile 16
        ContinueUnemploymentTT=[];% used fredfile 17
        TotalNFJOpenTT=[];% used fredfile 18
        ConstructionOpenTT=[];% used fredfile 19
        ManufacOpenTT=[];% used fredfile 20
        ProfOpenTT=[];% used fredfile 21
        HCareOpenTT=[];% used fredfile 22
        GovOpenTT=[];% used fredfile 23
        RealMedianPersIncomeTT=[];% used fredfile 24
        T10Y2YTT=[];% used fredfile 25
        fracrateinversion=0;% based on fredfile 25
        VisaDiscTT=[];% based on fred file 26
        CaseShillerTT=[];% based on fred file 27
        WeeklyWageTT=[];% based on fred file 28
        FYGDPTT=[];% based on fred file 29
        PublicDebtGDPTT=[];% based on fred file 30
        BudgetSurplusTT=[];% based on fred file 31
        NetFedOutlayTT=[];% based on fred file 32
        FedReceiptsTT=[];% based on fred file 33
        FedPublicDebtTT=[];% based on fred file 34
        FedGDPInterestTT=[];% based on fred file 35
        TreasuryDebtTT=[];% based on fred file 36
        DomAutoInvTT=[]; % based on fred file 37
        ForeignAutoSalesTT=[];% based on fred file 38
        TotVehSalesTT=[];% based on fred File 39
        DomesticAutoProdTT=[];%based on fred file 40
        AutoExportsTT=[];% based on fred file 41
        VehicleMilesTT=[];% based on fred file 42
        FreightIndexTT=[];% based on fred file 43
        RailCarLoadsTT=[];% based on fred file 44
        AirLoadTT=[];% based on fred file 45
        ASMTT=[];% based on fred file 46
        PipelinePetrolTT=[];% based on fred file 47
        HouseStartsTT=[];% based on fred file 48
        MDSPTT=[];% based on fred file 49
        VacHouseUnitsTT=[];% based on fred file 50
        USPatentsTT=[];% based on fred file 51
        TCUTT=[];% based on fred file 52
        SemiconductorsTT=[];% based on fred file 53 
        DefenseTT=[];% based on fred file 54
        TotHospRevenueTT=[];% based on fred file 55
        PharmaPriceTT=[];% based on fred file 56
        ProdPriceTT=[];% based on fred file 57
        FlexCPITT=[];% based on fred file 58
        CompHousesTT=[];% based on fred file 59
        AdvRetailSalesTT=[];%based on fred file 60
        ECommRSalesTT=[];% based on fred file 61
        InventorySalesTT=[];% based on fred file 62;
        RetailInvenTT=[];% based on fred file 63
        UsedCarSalesTT=[];% based on fred file 64
        RestaurantSalesTT=[];% based on fred file 65
        FurnitureSalesTT=[];%based on fred file 66
        ManufacturingSalesTT=[];%based on file 67
        NewCarSalesTT=[];% based on fred file 68
        FullServeRestaurantsTT=[];% based on fred file 69
        GasSalesTT=[];% based on fred file 70
        AutoPartsTT=[];% based on fred file 71
        LeadIndexTT=[];% based on fred file 72
        InferRecessionDatesTT=[];%based on fred file 73
        RecessionDatesRTT=[];% additional output from fredfile 73
        GDPRecessionFrac=0;% based on fred file 73
        CoEconomicActivityTT=[];% based on fred file 74;
        BankBalanceTT=[];% based on fred file 75
        CreditCardTT=[];% based on fred file 76
        LoanPerfTT=[];% based on fred file 77
        PopulationTT=[];% based on fred file 78
        TotHouseHoldsTT=[];% based on fred file 79
        POP55TT=[];% based on fred file 80
        POP2554TT=[];% based on fred file 81
        FamWChildTT=[];%based on fred file 82
        BlackPopTT=[];%based on fred file 83
        WhitePopTT=[];% based on fred file 84
        HispanicPopTT=[];% based on fred file 85
        FemaleERatioTT=[];% based on fred file 86;
        CBOENasdaqVolTT=[];%based on fred file 87
        LeadingIndexTT=[];% based on fred file 88
        Fed3MonthBondsTT=[];% used fredfile 89
        TDSPTT=[];% used fredfile90
        CDSPTT=[];% used fredfile91
        RDIncTT=[];% used fredfile92
        PCETT=[];% used fredfile93
        DAUTOTT=[];% used fredfile94
        THPITT=[];% used fredfile95
        CCBALTT=[];% used fredfile96
        LBANKLORTT=[];% used fredfile97
        PastDueMorTT=[];%used fredfile98
        CreditScoreTT=[];%used fredfile99
        HomeEquityTT=[];%used fredfile100
        USDPoundsTT=[];% used fredfile101
        USDBroadIndexTT=[];% used fredfile102
        JapYenUSDTT=[];% used fredfile103
        StockMktCapTT=[];% used fredfile104
        CPIAllTT=[];%used fredfile105
        GNATIncTT=[];%used fredfile106
        GASREGTT=[];% used fredfile107
        BrentEUTT=[];% used fredfile108
        EggPriceTT=[];% used fredfile109
        GroundBeefPriceTT=[];%used fredfile110
        ElectricityPriceTT=[];%used fredfile111
        WestTexasCrudeTT=[];%used fredfile112
        HHubNatGasPriceTT=[];%used fredfile113
        CopperPriceTT=[];%used fredfile114
        DieselPriceTT=[];%used fredfile115
        JetFuelPriceTT=[];%used fredfile116
        AluminumTT=[];%used fredfile117
        CocoaTT=[];% used fredfile118
        GlobalEnergyTT=[];% used fredfile119
        BreadPriceTT=[];% used fredfile120
        WheatPriceTT=[];% used fredfile121
        UraniumPriceTT=[];%used fredfile122
        NickelPriceTT=[];%used fredfile123
        RubberPriceTT=[];% used fredfile124
        SugarPriceTT=[];% used fredfile125
        UrbanHFTT=[];% used fredfile126
        PPIFoodTT=[];% used fredfile127 
        PPIDieselTT=[];% used fredfile128
        BolognaTT=[];% used fredfile129
        BonelessHamTT=[];%used fredfile130
        ChuckRoastTT=[];%used fredfile131
        BaconPriceTT=[];%used fredfile132
        SoybeanIndexTT=[];%used fredfile133
        FlourPriceTT=[];%used fredfile134
        CookingOilTT=[];% used fredfile135
        WholeChickenTT=[];% used fredfile136
        FarmProductsTT=[];% used fredfile137
        CattleTT=[];% used fredfile138
        TomatoesTT=[];% used fredfile139
        CornTT=[];% used fredfile140
        RawMilkTT=[]; %used fredfile141
        PCIFruitsTT=[]; %used fredfile142
        PPICabbageTT=[];%used fredfile143
        RiceTT=[];%used fredfile144
        PPICitrusTT=[];%used fredfile145
        RecessProbTT=[];%used fredfile146
        BudgetSurplus=[];
        BudgetDeficit=[];
        BudgetDeficitFraction=0;
        SmoothedRessProb=0;
        ishowrecession=0;
        barval=1;
        LogoFileName='FredLogo.jpg';
        iLogo=1;
        govjpegpath='K:\Investing2\gov_jpeg\'; 
        tiffpath='D:\Investing2\FRED_Data\Tiff_Files\';
        MSpath=[];
        jpegpath=[];
        excelpath=[];
        logfilepath=[];
        FredJpegList=[];
        FredPngList=[];
        SourceFile;
        Code;
        Desc;
        Freq;
        StartYear;
        EndYear;
        SeasonalAdj;
        BaseYear;
        NumObs;
        Chap;
        Section;
        fid;
        vert1;
        hor1;
        widd;
        lend;
        lend2;
        vert2;
        hor2;
        machine;
        chart_time;
        igrid=1;
        Fz1;
        Fz2;
        icapture=1;
        iCreatePDFReport=[];
        RptGenPresent=[];
        GrowthRate=0;
        GrowthRateAll=NaN(145,1);
        SG1=0;
        SG2=0;
        SG3=0;
        SG4=0;
        SG5=0;
        SG6=0;
        SG7=0;
        SG8=0;
        SG9=0;
        SG10=0;
        SG11=0;
        SG12=0;
        SG13=0;
        SG14=0;
        SG15=0;
        SG16=0;
        SG17=0;
        SG18=0;
        SG19=0;
        SG20=0;
        SG21=0;
        SG22=0;
        SG23=0;
        SG24=0;
        SG27=0;
        SG28=0;
        SG29=0;
        SG30=0;
        SG31=0;
        SG32=0;
        SG33=0;
        SG34=0;
        SG35=0;
        SG36=0;
        SG37=0;
        SG38=0;
        SG39=0;
        SG40=0;
        SG41=0;
        SG42=0;
        SG44=0;
        SG45=0;
        SG46=0;
        SG47=0;
        SG48=0;
        SG51=0;
        SG53=0;
        SG54=0;
        SG55=0;
        SG56=0;
        SG57=0;
        SG58=0;
        SG59=0;
        SG60=0;
        SG61=0;
        SG62=0;
        SG62x=0;
        SG63=0;
        SG64=0;
        SG65=0;
        SG66=0;
        SG67=0;
        SG68=0;
        SG69=0;
        SG70=0;
        SG71=0;
        SG75=0;
        SG76=0;
        SG78=0;
        SG79=0;
        SG80=0;
        SG81=0;
        SG82=0;
        SG83=0;
        SG84=0;
        SG85=0;
        SG86=0;
        SG87=0;
        SG88=0;
        SG89=0;
        SG90=0;
        SG91=0;
        SG92=0;
        SG93=0;
        SG94=0;
        SG95=0;
        SG96=0;
        SG97=0;
        SG98=0;
        SG99=0;
        SG100=0;
        SG101=0;
        SG102=0;
        SG103=0;
        SG104=0;
        SG105=0;
        SG106=0;
        SG107=0;
        SG108=0;
        SG109=0;
        SG110=0;
        SG111=0;
        SG112=0;
        SG113=0;
        SG114=0
        SG115=0;
        SG116=0;
        SG117=0;
        SG118=0;
        SG119=0;
        SG120=0;
        SG121=0;
        SG122=0;
        SG123=0;
        SG124=0;
        SG125=0;
        SG126=0;
        SG127=0;
        SG128=0;
        SG129=0;
        SG130=0;
        SG131=0;
        SG132=0;
        SG133=0;
        SG134=0;
        SG135=0;
        SG136=0;
        SG137=0;
        SG138=0;
        SG139=0;
        SG140=0;
        SG141=0;
        SG142=0;
        SG143=0;
        SG144=0;
        SG145=0;
        SG146=0;
        CurrentMedianValue=0;
        DataDist=zeros(146,20);
        DataMarks=zeros(20,1);

    end

    methods
        function obj = SimpleGrowth(obj,P0,PF,NYears)
            % Caclulate a simple annual growth rate in %
            gr=(log(PF)-log(P0))/NYears;
            obj.GrowthRate = gr;
        end

        function obj = SimpleGrowthAll(obj,P0,PF,NYears,itype)
            % Caclulate a simple annual growth rate in %
            gr=(log(PF)-log(P0))/NYears;
            obj.GrowthRateAll(itype) = gr;
            ab=1;
        end

        function obj = SimpleStats(obj,Data,itype)
            % Caclulate a simple set of distribution stats
            % Before proceeding remove an NaN Values
            DataNM=rmmissing(Data);
            numvals=length(DataNM);
            if(numvals>=100)
                if(itype==5)
                    ab=1;
                end
                DataSort=sort(DataNM);
                np05=round(.05*numvals);
                np10=round(.10*numvals);
                np15=round(.15*numvals);
                np20=round(.20*numvals);
                np25=round(.25*numvals);
                np30=round(.30*numvals);
                np35=round(.35*numvals);
                np40=round(.40*numvals);
                np45=round(.45*numvals);
                np50=round(.50*numvals);
                np55=round(.55*numvals);
                np60=round(.60*numvals);
                np65=round(.65*numvals);
                np70=round(.70*numvals);
                np75=round(.75*numvals);
                np80=round(.80*numvals);
                np85=round(.85*numvals);
                np90=round(.90*numvals);
                np95=round(.90*numvals);
                np100=round(numvals);
                val05=DataSort(np05,1);
                val10=DataSort(np10,1);
                val15=DataSort(np15,1);
                val20=DataSort(np20,1);
                val25=DataSort(np25,1);
                val30=DataSort(np30,1);
                val35=DataSort(np35,1);
                val40=DataSort(np40,1);
                val45=DataSort(np45,1);
                val50=DataSort(np50,1);
                val55=DataSort(np55,1);
                val60=DataSort(np60,1);
                val65=DataSort(np65,1);
                val70=DataSort(np70,1);
                val75=DataSort(np75,1);
                val80=DataSort(np80,1);
                val85=DataSort(np85,1);
                val90=DataSort(np90,1);
                val95=DataSort(np95,1);
                val100=DataSort(np100,1);
                obj.DataMarks(1,1)=5;
                obj.DataMarks(2,1)=10;
                obj.DataMarks(3,1)=15;
                obj.DataMarks(4,1)=20;
                obj.DataMarks(5,1)=25;
                obj.DataMarks(6,1)=30;
                obj.DataMarks(7,1)=35;
                obj.DataMarks(8,1)=40;
                obj.DataMarks(9,1)=45;
                obj.DataMarks(10,1)=50;
                obj.DataMarks(11,1)=55;
                obj.DataMarks(12,1)=60;
                obj.DataMarks(13,1)=65;
                obj.DataMarks(14,1)=70;
                obj.DataMarks(15,1)=75;
                obj.DataMarks(16,1)=80;
                obj.DataMarks(17,1)=85;
                obj.DataMarks(18,1)=90;
                obj.DataMarks(19,1)=95;
                obj.DataMarks(20,1)=100;
                obj.DataDist(itype,1)=val05;
                obj.DataDist(itype,2)=val10;
                obj.DataDist(itype,3)=val15;
                obj.DataDist(itype,4)=val20;
                obj.DataDist(itype,5)=val25;
                obj.DataDist(itype,6)=val30;
                obj.DataDist(itype,7)=val35;
                obj.DataDist(itype,8)=val40;
                obj.DataDist(itype,9)=val45;
                obj.DataDist(itype,10)=val50;
                obj.DataDist(itype,11)=val55;
                obj.DataDist(itype,12)=val60;
                obj.DataDist(itype,13)=val65;
                obj.DataDist(itype,14)=val70;
                obj.DataDist(itype,15)=val75;
                obj.DataDist(itype,16)=val80;
                obj.DataDist(itype,17)=val85;
                obj.DataDist(itype,18)=val90;
                obj.DataDist(itype,19)=val95;
                obj.DataDist(itype,20)=val100;

            else % Need at least a hundred data points to calculate

            end
        end
 
    end
end